//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class yuanquanEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“yuanquanEntities”部分中的连接字符串初始化新 yuanquanEntities 对象。
        /// </summary>
        public yuanquanEntities() : base("name=yuanquanEntities", "yuanquanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 yuanquanEntities 对象。
        /// </summary>
        public yuanquanEntities(string connectionString) : base(connectionString, "yuanquanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 yuanquanEntities 对象。
        /// </summary>
        public yuanquanEntities(EntityConnection connection) : base(connection, "yuanquanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<admin> admin
        {
            get
            {
                if ((_admin == null))
                {
                    _admin = base.CreateObjectSet<admin>("admin");
                }
                return _admin;
            }
        }
        private ObjectSet<admin> _admin;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<cha_problems> cha_problems
        {
            get
            {
                if ((_cha_problems == null))
                {
                    _cha_problems = base.CreateObjectSet<cha_problems>("cha_problems");
                }
                return _cha_problems;
            }
        }
        private ObjectSet<cha_problems> _cha_problems;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<challenge> challenge
        {
            get
            {
                if ((_challenge == null))
                {
                    _challenge = base.CreateObjectSet<challenge>("challenge");
                }
                return _challenge;
            }
        }
        private ObjectSet<challenge> _challenge;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<coder> coder
        {
            get
            {
                if ((_coder == null))
                {
                    _coder = base.CreateObjectSet<coder>("coder");
                }
                return _coder;
            }
        }
        private ObjectSet<coder> _coder;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<coder_cha> coder_cha
        {
            get
            {
                if ((_coder_cha == null))
                {
                    _coder_cha = base.CreateObjectSet<coder_cha>("coder_cha");
                }
                return _coder_cha;
            }
        }
        private ObjectSet<coder_cha> _coder_cha;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<combo> combo
        {
            get
            {
                if ((_combo == null))
                {
                    _combo = base.CreateObjectSet<combo>("combo");
                }
                return _combo;
            }
        }
        private ObjectSet<combo> _combo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<enterprise> enterprise
        {
            get
            {
                if ((_enterprise == null))
                {
                    _enterprise = base.CreateObjectSet<enterprise>("enterprise");
                }
                return _enterprise;
            }
        }
        private ObjectSet<enterprise> _enterprise;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<problem> problem
        {
            get
            {
                if ((_problem == null))
                {
                    _problem = base.CreateObjectSet<problem>("problem");
                }
                return _problem;
            }
        }
        private ObjectSet<problem> _problem;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 admin EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToadmin(admin admin)
        {
            base.AddObject("admin", admin);
        }
    
        /// <summary>
        /// 用于向 cha_problems EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocha_problems(cha_problems cha_problems)
        {
            base.AddObject("cha_problems", cha_problems);
        }
    
        /// <summary>
        /// 用于向 challenge EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTochallenge(challenge challenge)
        {
            base.AddObject("challenge", challenge);
        }
    
        /// <summary>
        /// 用于向 coder EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocoder(coder coder)
        {
            base.AddObject("coder", coder);
        }
    
        /// <summary>
        /// 用于向 coder_cha EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocoder_cha(coder_cha coder_cha)
        {
            base.AddObject("coder_cha", coder_cha);
        }
    
        /// <summary>
        /// 用于向 combo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocombo(combo combo)
        {
            base.AddObject("combo", combo);
        }
    
        /// <summary>
        /// 用于向 enterprise EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToenterprise(enterprise enterprise)
        {
            base.AddObject("enterprise", enterprise);
        }
    
        /// <summary>
        /// 用于向 problem EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToproblem(problem problem)
        {
            base.AddObject("problem", problem);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class admin : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 admin 对象。
        /// </summary>
        /// <param name="a_id">a_id 属性的初始值。</param>
        public static admin Createadmin(global::System.Int32 a_id)
        {
            admin admin = new admin();
            admin.a_id = a_id;
            return admin;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 a_id
        {
            get
            {
                return _a_id;
            }
            set
            {
                if (_a_id != value)
                {
                    Ona_idChanging(value);
                    ReportPropertyChanging("a_id");
                    _a_id = StructuralObject.SetValidValue(value, "a_id");
                    ReportPropertyChanged("a_id");
                    Ona_idChanged();
                }
            }
        }
        private global::System.Int32 _a_id;
        partial void Ona_idChanging(global::System.Int32 value);
        partial void Ona_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String a_account
        {
            get
            {
                return _a_account;
            }
            set
            {
                Ona_accountChanging(value);
                ReportPropertyChanging("a_account");
                _a_account = StructuralObject.SetValidValue(value, true, "a_account");
                ReportPropertyChanged("a_account");
                Ona_accountChanged();
            }
        }
        private global::System.String _a_account;
        partial void Ona_accountChanging(global::System.String value);
        partial void Ona_accountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String a_pwd
        {
            get
            {
                return _a_pwd;
            }
            set
            {
                Ona_pwdChanging(value);
                ReportPropertyChanging("a_pwd");
                _a_pwd = StructuralObject.SetValidValue(value, true, "a_pwd");
                ReportPropertyChanged("a_pwd");
                Ona_pwdChanged();
            }
        }
        private global::System.String _a_pwd;
        partial void Ona_pwdChanging(global::System.String value);
        partial void Ona_pwdChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="cha_problems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cha_problems : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 cha_problems 对象。
        /// </summary>
        /// <param name="cha_id">cha_id 属性的初始值。</param>
        /// <param name="p_id">p_id 属性的初始值。</param>
        /// <param name="id">id 属性的初始值。</param>
        public static cha_problems Createcha_problems(global::System.Int32 cha_id, global::System.Int32 p_id, global::System.Int32 id)
        {
            cha_problems cha_problems = new cha_problems();
            cha_problems.cha_id = cha_id;
            cha_problems.p_id = p_id;
            cha_problems.id = id;
            return cha_problems;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cha_id
        {
            get
            {
                return _cha_id;
            }
            set
            {
                Oncha_idChanging(value);
                ReportPropertyChanging("cha_id");
                _cha_id = StructuralObject.SetValidValue(value, "cha_id");
                ReportPropertyChanged("cha_id");
                Oncha_idChanged();
            }
        }
        private global::System.Int32 _cha_id;
        partial void Oncha_idChanging(global::System.Int32 value);
        partial void Oncha_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 p_id
        {
            get
            {
                return _p_id;
            }
            set
            {
                Onp_idChanging(value);
                ReportPropertyChanging("p_id");
                _p_id = StructuralObject.SetValidValue(value, "p_id");
                ReportPropertyChanged("p_id");
                Onp_idChanged();
            }
        }
        private global::System.Int32 _p_id;
        partial void Onp_idChanging(global::System.Int32 value);
        partial void Onp_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="challenge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class challenge : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 challenge 对象。
        /// </summary>
        /// <param name="cha_id">cha_id 属性的初始值。</param>
        public static challenge Createchallenge(global::System.Int32 cha_id)
        {
            challenge challenge = new challenge();
            challenge.cha_id = cha_id;
            return challenge;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cha_id
        {
            get
            {
                return _cha_id;
            }
            set
            {
                if (_cha_id != value)
                {
                    Oncha_idChanging(value);
                    ReportPropertyChanging("cha_id");
                    _cha_id = StructuralObject.SetValidValue(value, "cha_id");
                    ReportPropertyChanged("cha_id");
                    Oncha_idChanged();
                }
            }
        }
        private global::System.Int32 _cha_id;
        partial void Oncha_idChanging(global::System.Int32 value);
        partial void Oncha_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> e_id
        {
            get
            {
                return _e_id;
            }
            set
            {
                One_idChanging(value);
                ReportPropertyChanging("e_id");
                _e_id = StructuralObject.SetValidValue(value, "e_id");
                ReportPropertyChanged("e_id");
                One_idChanged();
            }
        }
        private Nullable<global::System.Int32> _e_id;
        partial void One_idChanging(Nullable<global::System.Int32> value);
        partial void One_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cha_type
        {
            get
            {
                return _cha_type;
            }
            set
            {
                Oncha_typeChanging(value);
                ReportPropertyChanging("cha_type");
                _cha_type = StructuralObject.SetValidValue(value, true, "cha_type");
                ReportPropertyChanged("cha_type");
                Oncha_typeChanged();
            }
        }
        private global::System.String _cha_type;
        partial void Oncha_typeChanging(global::System.String value);
        partial void Oncha_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cha_level
        {
            get
            {
                return _cha_level;
            }
            set
            {
                Oncha_levelChanging(value);
                ReportPropertyChanging("cha_level");
                _cha_level = StructuralObject.SetValidValue(value, true, "cha_level");
                ReportPropertyChanged("cha_level");
                Oncha_levelChanged();
            }
        }
        private global::System.String _cha_level;
        partial void Oncha_levelChanging(global::System.String value);
        partial void Oncha_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cha_public
        {
            get
            {
                return _cha_public;
            }
            set
            {
                Oncha_publicChanging(value);
                ReportPropertyChanging("cha_public");
                _cha_public = StructuralObject.SetValidValue(value, "cha_public");
                ReportPropertyChanged("cha_public");
                Oncha_publicChanged();
            }
        }
        private Nullable<global::System.Int32> _cha_public;
        partial void Oncha_publicChanging(Nullable<global::System.Int32> value);
        partial void Oncha_publicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> cha_date
        {
            get
            {
                return _cha_date;
            }
            set
            {
                Oncha_dateChanging(value);
                ReportPropertyChanging("cha_date");
                _cha_date = StructuralObject.SetValidValue(value, "cha_date");
                ReportPropertyChanged("cha_date");
                Oncha_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _cha_date;
        partial void Oncha_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncha_dateChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="coder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class coder : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 coder 对象。
        /// </summary>
        /// <param name="c_id">c_id 属性的初始值。</param>
        public static coder Createcoder(global::System.Int32 c_id)
        {
            coder coder = new coder();
            coder.c_id = c_id;
            return coder;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c_id
        {
            get
            {
                return _c_id;
            }
            set
            {
                if (_c_id != value)
                {
                    Onc_idChanging(value);
                    ReportPropertyChanging("c_id");
                    _c_id = StructuralObject.SetValidValue(value, "c_id");
                    ReportPropertyChanged("c_id");
                    Onc_idChanged();
                }
            }
        }
        private global::System.Int32 _c_id;
        partial void Onc_idChanging(global::System.Int32 value);
        partial void Onc_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String c_account
        {
            get
            {
                return _c_account;
            }
            set
            {
                Onc_accountChanging(value);
                ReportPropertyChanging("c_account");
                _c_account = StructuralObject.SetValidValue(value, true, "c_account");
                ReportPropertyChanged("c_account");
                Onc_accountChanged();
            }
        }
        private global::System.String _c_account;
        partial void Onc_accountChanging(global::System.String value);
        partial void Onc_accountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String c_pwd
        {
            get
            {
                return _c_pwd;
            }
            set
            {
                Onc_pwdChanging(value);
                ReportPropertyChanging("c_pwd");
                _c_pwd = StructuralObject.SetValidValue(value, true, "c_pwd");
                ReportPropertyChanged("c_pwd");
                Onc_pwdChanged();
            }
        }
        private global::System.String _c_pwd;
        partial void Onc_pwdChanging(global::System.String value);
        partial void Onc_pwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String c_name
        {
            get
            {
                return _c_name;
            }
            set
            {
                Onc_nameChanging(value);
                ReportPropertyChanging("c_name");
                _c_name = StructuralObject.SetValidValue(value, true, "c_name");
                ReportPropertyChanged("c_name");
                Onc_nameChanged();
            }
        }
        private global::System.String _c_name;
        partial void Onc_nameChanging(global::System.String value);
        partial void Onc_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> c_value
        {
            get
            {
                return _c_value;
            }
            set
            {
                Onc_valueChanging(value);
                ReportPropertyChanging("c_value");
                _c_value = StructuralObject.SetValidValue(value, "c_value");
                ReportPropertyChanged("c_value");
                Onc_valueChanged();
            }
        }
        private Nullable<global::System.Int32> _c_value;
        partial void Onc_valueChanging(Nullable<global::System.Int32> value);
        partial void Onc_valueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> c_speed
        {
            get
            {
                return _c_speed;
            }
            set
            {
                Onc_speedChanging(value);
                ReportPropertyChanging("c_speed");
                _c_speed = StructuralObject.SetValidValue(value, "c_speed");
                ReportPropertyChanged("c_speed");
                Onc_speedChanged();
            }
        }
        private Nullable<global::System.Double> _c_speed;
        partial void Onc_speedChanging(Nullable<global::System.Double> value);
        partial void Onc_speedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> c_accuracy
        {
            get
            {
                return _c_accuracy;
            }
            set
            {
                Onc_accuracyChanging(value);
                ReportPropertyChanging("c_accuracy");
                _c_accuracy = StructuralObject.SetValidValue(value, "c_accuracy");
                ReportPropertyChanged("c_accuracy");
                Onc_accuracyChanged();
            }
        }
        private Nullable<global::System.Double> _c_accuracy;
        partial void Onc_accuracyChanging(Nullable<global::System.Double> value);
        partial void Onc_accuracyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> c_quality
        {
            get
            {
                return _c_quality;
            }
            set
            {
                Onc_qualityChanging(value);
                ReportPropertyChanging("c_quality");
                _c_quality = StructuralObject.SetValidValue(value, "c_quality");
                ReportPropertyChanged("c_quality");
                Onc_qualityChanged();
            }
        }
        private Nullable<global::System.Double> _c_quality;
        partial void Onc_qualityChanging(Nullable<global::System.Double> value);
        partial void Onc_qualityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> c_standard
        {
            get
            {
                return _c_standard;
            }
            set
            {
                Onc_standardChanging(value);
                ReportPropertyChanging("c_standard");
                _c_standard = StructuralObject.SetValidValue(value, "c_standard");
                ReportPropertyChanged("c_standard");
                Onc_standardChanged();
            }
        }
        private Nullable<global::System.Double> _c_standard;
        partial void Onc_standardChanging(Nullable<global::System.Double> value);
        partial void Onc_standardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String c_skill
        {
            get
            {
                return _c_skill;
            }
            set
            {
                Onc_skillChanging(value);
                ReportPropertyChanging("c_skill");
                _c_skill = StructuralObject.SetValidValue(value, true, "c_skill");
                ReportPropertyChanged("c_skill");
                Onc_skillChanged();
            }
        }
        private global::System.String _c_skill;
        partial void Onc_skillChanging(global::System.String value);
        partial void Onc_skillChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="coder_cha")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class coder_cha : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 coder_cha 对象。
        /// </summary>
        /// <param name="c_id">c_id 属性的初始值。</param>
        /// <param name="cha_id">cha_id 属性的初始值。</param>
        /// <param name="id">id 属性的初始值。</param>
        public static coder_cha Createcoder_cha(global::System.Int32 c_id, global::System.Int32 cha_id, global::System.Int32 id)
        {
            coder_cha coder_cha = new coder_cha();
            coder_cha.c_id = c_id;
            coder_cha.cha_id = cha_id;
            coder_cha.id = id;
            return coder_cha;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c_id
        {
            get
            {
                return _c_id;
            }
            set
            {
                Onc_idChanging(value);
                ReportPropertyChanging("c_id");
                _c_id = StructuralObject.SetValidValue(value, "c_id");
                ReportPropertyChanged("c_id");
                Onc_idChanged();
            }
        }
        private global::System.Int32 _c_id;
        partial void Onc_idChanging(global::System.Int32 value);
        partial void Onc_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cha_id
        {
            get
            {
                return _cha_id;
            }
            set
            {
                Oncha_idChanging(value);
                ReportPropertyChanging("cha_id");
                _cha_id = StructuralObject.SetValidValue(value, "cha_id");
                ReportPropertyChanged("cha_id");
                Oncha_idChanged();
            }
        }
        private global::System.Int32 _cha_id;
        partial void Oncha_idChanging(global::System.Int32 value);
        partial void Oncha_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> grade
        {
            get
            {
                return _grade;
            }
            set
            {
                OngradeChanging(value);
                ReportPropertyChanging("grade");
                _grade = StructuralObject.SetValidValue(value, "grade");
                ReportPropertyChanged("grade");
                OngradeChanged();
            }
        }
        private Nullable<global::System.Int32> _grade;
        partial void OngradeChanging(Nullable<global::System.Int32> value);
        partial void OngradeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usetime
        {
            get
            {
                return _usetime;
            }
            set
            {
                OnusetimeChanging(value);
                ReportPropertyChanging("usetime");
                _usetime = StructuralObject.SetValidValue(value, "usetime");
                ReportPropertyChanged("usetime");
                OnusetimeChanged();
            }
        }
        private Nullable<global::System.Int32> _usetime;
        partial void OnusetimeChanging(Nullable<global::System.Int32> value);
        partial void OnusetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="combo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class combo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 combo 对象。
        /// </summary>
        /// <param name="com_id">com_id 属性的初始值。</param>
        public static combo Createcombo(global::System.Int32 com_id)
        {
            combo combo = new combo();
            combo.com_id = com_id;
            return combo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 com_id
        {
            get
            {
                return _com_id;
            }
            set
            {
                if (_com_id != value)
                {
                    Oncom_idChanging(value);
                    ReportPropertyChanging("com_id");
                    _com_id = StructuralObject.SetValidValue(value, "com_id");
                    ReportPropertyChanged("com_id");
                    Oncom_idChanged();
                }
            }
        }
        private global::System.Int32 _com_id;
        partial void Oncom_idChanging(global::System.Int32 value);
        partial void Oncom_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> com_price
        {
            get
            {
                return _com_price;
            }
            set
            {
                Oncom_priceChanging(value);
                ReportPropertyChanging("com_price");
                _com_price = StructuralObject.SetValidValue(value, "com_price");
                ReportPropertyChanged("com_price");
                Oncom_priceChanged();
            }
        }
        private Nullable<global::System.Int32> _com_price;
        partial void Oncom_priceChanging(Nullable<global::System.Int32> value);
        partial void Oncom_priceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> com_chanum
        {
            get
            {
                return _com_chanum;
            }
            set
            {
                Oncom_chanumChanging(value);
                ReportPropertyChanging("com_chanum");
                _com_chanum = StructuralObject.SetValidValue(value, "com_chanum");
                ReportPropertyChanged("com_chanum");
                Oncom_chanumChanged();
            }
        }
        private Nullable<global::System.Int32> _com_chanum;
        partial void Oncom_chanumChanging(Nullable<global::System.Int32> value);
        partial void Oncom_chanumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> com_currency
        {
            get
            {
                return _com_currency;
            }
            set
            {
                Oncom_currencyChanging(value);
                ReportPropertyChanging("com_currency");
                _com_currency = StructuralObject.SetValidValue(value, "com_currency");
                ReportPropertyChanged("com_currency");
                Oncom_currencyChanged();
            }
        }
        private Nullable<global::System.Int32> _com_currency;
        partial void Oncom_currencyChanging(Nullable<global::System.Int32> value);
        partial void Oncom_currencyChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="enterprise")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class enterprise : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 enterprise 对象。
        /// </summary>
        /// <param name="e_id">e_id 属性的初始值。</param>
        public static enterprise Createenterprise(global::System.Int32 e_id)
        {
            enterprise enterprise = new enterprise();
            enterprise.e_id = e_id;
            return enterprise;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 e_id
        {
            get
            {
                return _e_id;
            }
            set
            {
                if (_e_id != value)
                {
                    One_idChanging(value);
                    ReportPropertyChanging("e_id");
                    _e_id = StructuralObject.SetValidValue(value, "e_id");
                    ReportPropertyChanged("e_id");
                    One_idChanged();
                }
            }
        }
        private global::System.Int32 _e_id;
        partial void One_idChanging(global::System.Int32 value);
        partial void One_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String e_account
        {
            get
            {
                return _e_account;
            }
            set
            {
                One_accountChanging(value);
                ReportPropertyChanging("e_account");
                _e_account = StructuralObject.SetValidValue(value, true, "e_account");
                ReportPropertyChanged("e_account");
                One_accountChanged();
            }
        }
        private global::System.String _e_account;
        partial void One_accountChanging(global::System.String value);
        partial void One_accountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String e_pwd
        {
            get
            {
                return _e_pwd;
            }
            set
            {
                One_pwdChanging(value);
                ReportPropertyChanging("e_pwd");
                _e_pwd = StructuralObject.SetValidValue(value, true, "e_pwd");
                ReportPropertyChanged("e_pwd");
                One_pwdChanged();
            }
        }
        private global::System.String _e_pwd;
        partial void One_pwdChanging(global::System.String value);
        partial void One_pwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> e_chanum
        {
            get
            {
                return _e_chanum;
            }
            set
            {
                One_chanumChanging(value);
                ReportPropertyChanging("e_chanum");
                _e_chanum = StructuralObject.SetValidValue(value, "e_chanum");
                ReportPropertyChanged("e_chanum");
                One_chanumChanged();
            }
        }
        private Nullable<global::System.Int32> _e_chanum;
        partial void One_chanumChanging(Nullable<global::System.Int32> value);
        partial void One_chanumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> e_currency
        {
            get
            {
                return _e_currency;
            }
            set
            {
                One_currencyChanging(value);
                ReportPropertyChanging("e_currency");
                _e_currency = StructuralObject.SetValidValue(value, "e_currency");
                ReportPropertyChanged("e_currency");
                One_currencyChanged();
            }
        }
        private Nullable<global::System.Int32> _e_currency;
        partial void One_currencyChanging(Nullable<global::System.Int32> value);
        partial void One_currencyChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yuanquanModel", Name="problem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class problem : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 problem 对象。
        /// </summary>
        /// <param name="p_id">p_id 属性的初始值。</param>
        public static problem Createproblem(global::System.Int32 p_id)
        {
            problem problem = new problem();
            problem.p_id = p_id;
            return problem;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 p_id
        {
            get
            {
                return _p_id;
            }
            set
            {
                if (_p_id != value)
                {
                    Onp_idChanging(value);
                    ReportPropertyChanging("p_id");
                    _p_id = StructuralObject.SetValidValue(value, "p_id");
                    ReportPropertyChanged("p_id");
                    Onp_idChanged();
                }
            }
        }
        private global::System.Int32 _p_id;
        partial void Onp_idChanging(global::System.Int32 value);
        partial void Onp_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String p_title
        {
            get
            {
                return _p_title;
            }
            set
            {
                Onp_titleChanging(value);
                ReportPropertyChanging("p_title");
                _p_title = StructuralObject.SetValidValue(value, true, "p_title");
                ReportPropertyChanged("p_title");
                Onp_titleChanged();
            }
        }
        private global::System.String _p_title;
        partial void Onp_titleChanging(global::System.String value);
        partial void Onp_titleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String p_detail
        {
            get
            {
                return _p_detail;
            }
            set
            {
                Onp_detailChanging(value);
                ReportPropertyChanging("p_detail");
                _p_detail = StructuralObject.SetValidValue(value, true, "p_detail");
                ReportPropertyChanged("p_detail");
                Onp_detailChanged();
            }
        }
        private global::System.String _p_detail;
        partial void Onp_detailChanging(global::System.String value);
        partial void Onp_detailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String p_level
        {
            get
            {
                return _p_level;
            }
            set
            {
                Onp_levelChanging(value);
                ReportPropertyChanging("p_level");
                _p_level = StructuralObject.SetValidValue(value, true, "p_level");
                ReportPropertyChanged("p_level");
                Onp_levelChanged();
            }
        }
        private global::System.String _p_level;
        partial void Onp_levelChanging(global::System.String value);
        partial void Onp_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String p_answer
        {
            get
            {
                return _p_answer;
            }
            set
            {
                Onp_answerChanging(value);
                ReportPropertyChanging("p_answer");
                _p_answer = StructuralObject.SetValidValue(value, true, "p_answer");
                ReportPropertyChanged("p_answer");
                Onp_answerChanged();
            }
        }
        private global::System.String _p_answer;
        partial void Onp_answerChanging(global::System.String value);
        partial void Onp_answerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String p_type
        {
            get
            {
                return _p_type;
            }
            set
            {
                Onp_typeChanging(value);
                ReportPropertyChanging("p_type");
                _p_type = StructuralObject.SetValidValue(value, true, "p_type");
                ReportPropertyChanged("p_type");
                Onp_typeChanged();
            }
        }
        private global::System.String _p_type;
        partial void Onp_typeChanging(global::System.String value);
        partial void Onp_typeChanged();

        #endregion

    }

    #endregion

}
